export interface TranslationStrings {
  siteTitle: string;
  pageTitle: string;
  pageDesc: string;
  backToList: string;
  backToListFull: string;
  references: string;
  words: string;
  citations: string;
  figures: string;
  langLabel: string;
}

export const translations: Record<string, TranslationStrings> = {
  ko: {
    siteTitle: "NAVI Research",
    pageTitle: "연구 세션",
    pageDesc: "시뮬레이션으로 생성된 논문을 열람합니다",
    backToList: "← 목록으로",
    backToListFull: "← 목록으로 돌아가기",
    references: "참고문헌",
    words: "단어",
    citations: "인용",
    figures: "그림",
    langLabel: "EN",
  },
  en: {
    siteTitle: "NAVI Research",
    pageTitle: "Research Sessions",
    pageDesc: "Browse papers generated by simulation",
    backToList: "← Back",
    backToListFull: "← Back to list",
    references: "References",
    words: "words",
    citations: "citations",
    figures: "fig",
    langLabel: "한",
  },
};

export type Locale = "ko" | "en";
