export interface TranslationStrings {
  siteTitle: string;
  pageTitle: string;
  pageDesc: string;
  backToList: string;
  backToListFull: string;
  references: string;
  words: string;
  citations: string;
  figures: string;
  langLabel: string;
  ptcs: string;
  typeResearchPaper: string;
  typeLiteratureReview: string;
  typeReport: string;
}

export const translations: Record<string, TranslationStrings> = {
  ko: {
    siteTitle: "NAVI Research",
    pageTitle: "연구 세션",
    pageDesc: "시뮬레이션으로 생성된 논문을 열람합니다",
    backToList: "← 목록으로",
    backToListFull: "← 목록으로 돌아가기",
    references: "참고문헌",
    words: "단어",
    citations: "인용",
    figures: "그림",
    langLabel: "EN",
    ptcs: "투고 가능성",
    typeResearchPaper: "연구 논문",
    typeLiteratureReview: "문헌 리뷰",
    typeReport: "보고서",
  },
  en: {
    siteTitle: "NAVI Research",
    pageTitle: "Research Sessions",
    pageDesc: "Browse papers generated by simulation",
    backToList: "← Back",
    backToListFull: "← Back to list",
    references: "References",
    words: "words",
    citations: "citations",
    figures: "fig",
    langLabel: "한",
    ptcs: "PTCS",
    typeResearchPaper: "Research Paper",
    typeLiteratureReview: "Literature Review",
    typeReport: "Report",
  },
};

export type Locale = "ko" | "en";

// Helper to translate paper type
export function translateType(type: string, t: TranslationStrings): string {
  switch (type) {
    case "Research Paper": return t.typeResearchPaper;
    case "Literature Review": return t.typeLiteratureReview;
    case "Report": return t.typeReport;
    default: return type;
  }
}
